RTS_Mensajeria/Controllers/NivelesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RTS_Mensajeria.Models.DB_Model;

namespace RTS_Mensajeria.Controllers
{
    public class NivelesController : BaseController
    {
        private RTS_MensajeriaEntities db = new RTS_MensajeriaEntities();

        // GET: Niveles
        public ActionResult Index()
        {
            return View(db.Nivel.ToList());
        }

        // GET: Niveles
        public ActionResult Inactive()
        {
            return View(db.Nivel.ToList());
        }

        // GET: Niveles/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nivel nivel = db.Nivel.Find(id);
            if (nivel == null)
            {
                return HttpNotFound();
            }
            return View(nivel);
        }

        // GET: Niveles/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Niveles/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_Nivel,Ubicacion,Descripcion,Estado")] Nivel nivel)
        {
            if (ModelState.IsValid)
            {
                db.Nivel.Add(nivel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nivel);
        }

        // GET: Niveles/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nivel nivel = db.Nivel.Find(id);
            if (nivel == null)
            {
                return HttpNotFound();
            }
            return View(nivel);
        }

        // POST: Niveles/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_Nivel,Ubicacion,Descripcion,Estado")] Nivel nivel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nivel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nivel);
        }

        // GET: Niveles/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nivel nivel = db.Nivel.Find(id);
            if (nivel == null)
            {
                return HttpNotFound();
            }
            return View(nivel);
        }

        // POST: Niveles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Nivel nivel = db.Nivel.Find(id);
            nivel.Estado = "Inactivo";
            db.Entry(nivel).State = EntityState.Modified;
            db.SaveChanges();
            /*db.Nivel.Remove(nivel);
            db.SaveChanges();*/
            return RedirectToAction("Index");
        }

        // GET: Niveles/Active/5
        public ActionResult Active(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nivel nivel = db.Nivel.Find(id);
            if (nivel == null)
            {
                return HttpNotFound();
            }
            return View(nivel);
        }

        // POST: Niveles/Active/5
        [HttpPost, ActionName("Active")]
        [ValidateAntiForgeryToken]
        public ActionResult ActiveConfirmed(int id)
        {
            Nivel nivel = db.Nivel.Find(id);
            nivel.Estado = "Activo";
            db.Entry(nivel).State = EntityState.Modified;
            db.SaveChanges();
            /*db.Nivel.Remove(nivel);
            db.SaveChanges();*/
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RTS_Mensajeria/Views/Niveles/Active.cshtml
@model RTS_Mensajeria.Models.DB_Model.Nivel
@{
    ViewBag.Title = "Activar nivel";
}
@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="card card-cascade narrower">
        <div class="view view-cascade primary-color narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
            <h4 class="ml-3 mb-2 mb-sm-0 pt-1 white-text">
                <span><a href="@Url.Action("Index","Home")" class="text-decoration-none white-text"><i class="fa fa-home mr-1"></i> Inicio</a></span>
                <span>/</span>
                <span><a href="@Url.Action("Index", "Niveles")" class="text-decoration-none white-text"><i class="fa fa-building mr-1"></i> Niveles</a></span>
                <span>/</span>
                <span>Activar nivel</span>
            </h4>
            <div class="mr-3">
                <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2">
                    <i class="fas fa-info-circle mt-0"></i>
                </button>
            </div>
        </div>
        <div class="px-4">
            <div class="table-wrapper">
                <br />
                <div class="row">
                    <div class="col-md-10">
                        <h2>Activar el nivel</h2>
                    </div>
                </div>
                <hr />
                <div>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Ubicacion)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Ubicacion)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Descripcion)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Descripcion)
                        </dd>
                    </dl>
                    <hr />
                    <div class="text-center">
                        <h3>¿Desea activar éste nivel?</h3>
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <a class="btn btn-primary" href="@Url.Action("Inactive", "Niveles")">
                                    <i class="fa fa-arrow-left mr-1"></i> Regresar
                                </a>
                                |
                                <button type="submit" class="btn green btn-green">
                                    <i class="fa fa-check mr-1"></i>
                                    Activar
                                </button>
                            </div>
                            <br />
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
}

RTS_Mensajeria/Views/Niveles/Create.cshtml
@model RTS_Mensajeria.Models.DB_Model.Nivel
@{
    ViewBag.Title = "Crear nivel";
}
@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="card card-cascade narrower">
        <div class="view view-cascade primary-color narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
            <h4 class="ml-3 mb-2 mb-sm-0 pt-1 white-text">
                <span><a href="@Url.Action("Index","Home")" class="text-decoration-none white-text"><i class="fa fa-home mr-1"></i> Inicio</a></span>
                <span>/</span>
                <span><a href="@Url.Action("Index", "Nivel")" class="text-decoration-none white-text"><i class="fa fa-building mr-1"></i> Niveles</a></span>
                <span>/</span>
                <span>Agregar nivel</span>
            </h4>
            <div class="mr-3">
                <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2">
                    <i class="fas fa-info-circle mt-0"></i>
                </button>
            </div>
        </div>
        <div class="px-4">
            <div class="table-wrapper">
                <br />
                <div class="row">
                    <div class="col-md-10">
                        <h2>Nuevo nivel</h2>
                    </div>
                </div>
                <hr />
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    @Html.HiddenFor(model => model.Estado, new { @Value = "Activo"})
                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Ubicacion, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.Ubicacion, new SelectList(new List<Object>{
                                    new { value = "Comercial" , text = "Comercial"  },
                                    new { value = "Edificio" , text = "Edificio" }},
                                    "value", "text", 2), new { @class = "mdb-select md-form" })
                                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                                @Html.ValidationMessageFor(model => model.Ubicacion, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "md-form md-textarea" } })
                                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="form-group text-right">
                            <div class="col-md-offset-2 col-md-10">
                                <a class="btn btn-primary" href="@Url.Action("Index", "Niveles")"><i class="fa fa-arrow-left mr-1"></i> Regresar</a>
                                |
                                <button type="submit" class="btn btn-default"><i class="fas fa-magic ml-1"></i> Crear </button>
                            </div>
                        </div>
                    </div>
                }
                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }
            </div>
        </div>
    </div>
}

RTS_Mensajeria/Views/Niveles/Delete.cshtml
@model RTS_Mensajeria.Models.DB_Model.Nivel
@{
    ViewBag.Title = "Eliminar nivel";
}
@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="card card-cascade narrower">
        <div class="view view-cascade primary-color narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
            <h4 class="ml-3 mb-2 mb-sm-0 pt-1 white-text">
                <span><a href="@Url.Action("Index","Home")" class="text-decoration-none white-text"><i class="fa fa-home mr-1"></i> Inicio</a></span>
                <span>/</span>
                <span><a href="@Url.Action("Index", "Niveles")" class="text-decoration-none white-text"><i class="fa fa-building mr-1"></i> Niveles</a></span>
                <span>/</span>
                <span>Eliminar nivel</span>
            </h4>
            <div class="mr-3">
                <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2">
                    <i class="fas fa-info-circle mt-0"></i>
                </button>
            </div>
        </div>
        <div class="px-4">
            <div class="table-wrapper">
                <br />
                <div class="row">
                    <div class="col-md-10">
                        <h2>Eliminar el nivel</h2>
                    </div>
                </div>
                <hr />
                <div>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Ubicacion)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Ubicacion)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Descripcion)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Descripcion)
                        </dd>
                    </dl>
                    <hr />
                    <div class="text-center">
                        <h3>¿Desea eliminar éste nivel?</h3>
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <a class="btn btn-primary" href="@Url.Action("Index", "Niveles")">
                                    <i class="fa fa-arrow-left mr-1"></i> Regresar
                                </a>
                                |
                                <button type="submit" class="btn btn-default">
                                    <i class="fa fa-times mr-1"></i>
                                    Eliminar
                                </button>
                            </div>
                            <br />
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
}

RTS_Mensajeria/Views/Niveles/Details.cshtml
@model RTS_Mensajeria.Models.DB_Model.Nivel

@{
    ViewBag.Title = "Detalles del nivel";
}

@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="card card-cascade narrower">
        <div class="view view-cascade primary-color narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
            <h4 class="ml-3 mb-2 mb-sm-0 pt-1 white-text">
                <span><a href="@Url.Action("Index","Home")" class="text-decoration-none white-text"><i class="fa fa-home mr-1"></i> Inicio</a></span>
                <span>/</span>
                <span><a href="@Url.Action("Index", "Niveles")" class="text-decoration-none white-text"><i class="fa fa-building mr-1"></i> Niveles</a></span>
                <span>/</span>
                <span>Detalle del nivel</span>
            </h4>
            <div class="mr-3">
                <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2">
                    <i class="fas fa-info-circle mt-0"></i>
                </button>
            </div>
        </div>
        <div class="px-4">
            <div class="table-wrapper">
                <br />
                <div class="row">
                    <div class="col-md-10">
                        <h2>Detalle del nivel</h2>
                    </div>
                </div>
                <hr />
                <div>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Ubicacion)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Ubicacion)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Descripcion)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Descripcion)
                        </dd>
                    </dl>
                </div>
                <br />
                <div class="form-group text-right">
                    <div class="col-md-offset-2 col-md-10">
                        <a class="btn btn-primary" href="@Url.Action("Index", "Niveles")"><i class="fa fa-arrow-left mr-1"></i> Regresar</a>
                        |
                        <a href="@Url.Action("Edit", "Niveles", new { id = Model.Id_Nivel})" class="btn btn-default"><i class="fa fa-edit ml-1"></i> Editar </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

RTS_Mensajeria/Views/Niveles/Edit.cshtml
@model RTS_Mensajeria.Models.DB_Model.Nivel

@{
    ViewBag.Title = "Editar nivel";
}

@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{
    <div class="card card-cascade narrower">
        <div class="view view-cascade primary-color narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
            <h4 class="ml-3 mb-2 mb-sm-0 pt-1 white-text">
                <span><a href="@Url.Action("Index","Home")" class="text-decoration-none white-text"><i class="fa fa-home mr-1"></i> Inicio</a></span>
                <span>/</span>
                <span><a href="@Url.Action("Index", "Niveles")" class="text-decoration-none white-text"><i class="fa fa-building mr-1"></i> Niveles</a></span>
                <span>/</span>
                <span>Editar nivel</span>
            </h4>
            <div class="mr-3">
                <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2">
                    <i class="fas fa-info-circle mt-0"></i>
                </button>
            </div>
        </div>
        <div class="px-4">
            <div class="table-wrapper">
                <br />
                <div class="row">
                    <div class="col-md-10">
                        <h2>Editar Nivel</h2>
                    </div>
                </div>
                <hr />
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id_Nivel)
                        @Html.HiddenFor(model => model.Estado)
                        <div class="form-group">
                            @Html.LabelFor(model => model.Ubicacion, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownListFor(model => model.Ubicacion, new SelectList(new List<Object>{
                                    new { value = "Comercial" , text = "Comercial"  },
                                    new { value = "Edificio" , text = "Edificio" }},
                                    "value", "text", 2), new { @class = "mdb-select md-form" })
                                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                                @Html.ValidationMessageFor(model => model.Ubicacion, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "md-form md-textarea" } })
                                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="form-group text-right">
                            <div class="col-md-offset-2 col-md-10">
                                <a class="btn btn-primary" href="@Url.Action("Index", "Nivel")"><i class="fa fa-arrow-left mr-1"></i> Regresar</a>
                                |
                                <button type="submit" class="btn btn-default"><i class="fa fa-save ml-1"></i> Guardar </button>
                            </div>
                        </div>
                    </div>
                }
                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }
            </div>
        </div>
    </div>
}

RTS_Mensajeria/Views/Niveles/Inactive.cshtml
@model IEnumerable<RTS_Mensajeria.Models.DB_Model.Nivel>
@{
    ViewBag.Title = "Inicio";
}

@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{
    <div class="card card-cascade narrower">
        <div class="view view-cascade primary-color narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
            <h4 class="ml-3 mb-2 mb-sm-0 pt-1 white-text">
                <span><a href="@Url.Action("Index","Home")" class="text-decoration-none white-text"><i class="fa fa-home mr-1"></i> Inicio</a></span>
                <span>/</span>
                <span><i class="fa fa-building mr-1"></i> Niveles</span>
            </h4>
            <div class="mr-3">
                <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2">
                    <i class="fas fa-info-circle mt-0"></i>
                </button>
            </div>
        </div>
        <div class="px-4">
            <div class="table-wrapper">
                <br />
                <div class="row">
                    <div class="col-md-10">
                        <h2>Listado de niveles eliminados</h2>
                    </div>
                    <div class="col-md-2">
                        <a class="btn btn-default btn-small btn-rounded" href="@Url.Action("Create", "Niveles")">
                            <i class="fa fa-plus"></i> Crear
                        </a>
                    </div>
                </div>
                <br />
                <div class="table-responsive ">
                    <table class="table table-hover">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Descripcion)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Ubicacion)
                            </th>
                            <th>Acciones</th>
                        </tr>
                        @foreach (var item in Model)
                        {
                            if (item.Estado == "Inactivo")
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Descripcion)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Ubicacion)
                                    </td>
                                    <td>
                                        <a class="btn btn-sm btn-secondary" href="@Url.Action("Active", "Niveles", new { id = item.Id_Nivel })">
                                            <i class="fa fa-power-off"></i> Activar
                                        </a>
                                    </td>
                                </tr>
                            }
                        }
                    </table>
                </div>
            </div>
        </div>

    </div>
    <br />
}

RTS_Mensajeria/Views/Niveles/Index.cshtml
@model IEnumerable<RTS_Mensajeria.Models.DB_Model.Nivel>
@{
    ViewBag.Title = "Inicio";
}

@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{
    <div class="card card-cascade narrower">
        <div class="view view-cascade primary-color narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
            <h4 class="ml-3 mb-2 mb-sm-0 pt-1 white-text">
                <span><a href="@Url.Action("Index","Home")" class="text-decoration-none white-text"><i class="fa fa-home mr-1"></i> Inicio</a></span>
                <span>/</span>
                <span><i class="fa fa-building mr-1"></i> Niveles</span>
            </h4>
            <div class="mr-3">
                <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2">
                    <i class="fas fa-info-circle mt-0"></i>
                </button>
            </div>
        </div>
        <div class="px-4">
            <div class="table-wrapper">
                <br />
                <div class="row">
                    <div class="col-md-10">
                        <h2>Listado de niveles</h2>
                    </div>
                    <div class="col-md-2">
                        <a class="btn btn-default btn-small btn-rounded" href="@Url.Action("Create", "Niveles")">
                            <i class="fa fa-plus"></i> Crear
                        </a>
                    </div>
                </div>
                <br />
                <div class="table-responsive ">
                    <table class="table table-hover">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Descripcion)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Ubicacion)
                            </th>
                            <th>Acciones</th>
                        </tr>
                        @foreach (var item in Model)
                        {
                            if (item.Estado == "Activo")
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Descripcion)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Ubicacion)
                                    </td>
                                    <td>
                                        <a class="btn btn-sm btn-rounded green" href="@Url.Action("Edit", "Niveles", new { id = item.Id_Nivel })">
                                            <i class="fa fa-edit"></i> Editar
                                        </a>
                                        <a class="btn btn-sm btn-rounded blue" href="@Url.Action("Details", "Niveles", new { id = item.Id_Nivel })">
                                            <i class="fa fa-eye"></i> Detalle
                                        </a>
                                        <a class="btn btn-sm btn-rounded red" href="@Url.Action("Delete", "Niveles", new { id = item.Id_Nivel })">
                                            <i class="fa fa-trash"></i> Eliminar
                                        </a>
                                    </td>
                                </tr>
                            }
                        }
                    </table>
                </div>
            </div>
        </div>

    </div>
    <br />
}