RTS_Mensajeria/Models/DB_Model/HorarioEntrega.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTS_Mensajeria.Models.DB_Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class HorarioEntrega : BaseVM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HorarioEntrega()
        {
            this.IngresoProveedor = new HashSet<IngresoProveedor>();
        }
    
        public int Id_HorarioEntrega { get; set; }

        [DataType(DataType.Time)]
        [Display(Name = "Hora de entrega")]
        [Required(ErrorMessage = "Debe ingresar la hora entrega")]
        public Nullable<System.TimeSpan> Hora_Entrega { get; set; }

        [DataType(DataType.Time)]
        [Display(Name = "Hora de salida")]
        [Required(ErrorMessage = "Debe ingresar la hora salida")]
        public Nullable<System.TimeSpan> Hora_Salida { get; set; }

        [DefaultValue("Activo")]
        [StringLength(8, MinimumLength = 6)]
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngresoProveedor> IngresoProveedor { get; set; }
    }
}

RTS_Mensajeria/Controllers/HorarioEntregasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RTS_Mensajeria.Models.DB_Model;

namespace RTS_Mensajeria.Controllers
{
    public class HorarioEntregasController : BaseController
    {
        private RTS_MensajeriaEntities db = new RTS_MensajeriaEntities();

        // GET: HorarioEntregas
        public ActionResult Index()
        {
            return View(db.HorarioEntrega.ToList());
        }
        // GET: HorarioEntregas
        public ActionResult Inactive()
        {
            return View(db.HorarioEntrega.ToList());
        }

        // GET: HorarioEntregas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HorarioEntrega horarioEntrega = db.HorarioEntrega.Find(id);
            if (horarioEntrega == null)
            {
                return HttpNotFound();
            }
            return View(horarioEntrega);
        }

        // GET: HorarioEntregas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: HorarioEntregas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_HorarioEntrega,Hora_Entrega,Hora_Salida,Estado")] HorarioEntrega horarioEntrega)
        {
            if (ModelState.IsValid)
            {
                db.HorarioEntrega.Add(horarioEntrega);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(horarioEntrega);
        }

        // GET: HorarioEntregas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HorarioEntrega horarioEntrega = db.HorarioEntrega.Find(id);
            if (horarioEntrega == null)
            {
                return HttpNotFound();
            }
            return View(horarioEntrega);
        }

        // POST: HorarioEntregas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_HorarioEntrega,Hora_Entrega,Hora_Salida,Estado")] HorarioEntrega horarioEntrega)
        {
            if (ModelState.IsValid)
            {
                db.Entry(horarioEntrega).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(horarioEntrega);
        }

        // GET: HorarioEntregas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HorarioEntrega horarioEntrega = db.HorarioEntrega.Find(id);
            if (horarioEntrega == null)
            {
                return HttpNotFound();
            }
            return View(horarioEntrega);
        }

        // POST: HorarioEntregas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            HorarioEntrega horarioEntrega = db.HorarioEntrega.Find(id);
            horarioEntrega.Estado = "Inactivo";
            db.Entry(horarioEntrega).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: HorarioEntregas/Active/6
        public ActionResult Active(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HorarioEntrega horarioEntrega = db.HorarioEntrega.Find(id);
            if (horarioEntrega == null)
            {
                return HttpNotFound();
            }
            return View(horarioEntrega);
        }

        // POST: HorarioEntregas/Active/6
        [HttpPost, ActionName("Active")]
        [ValidateAntiForgeryToken]
        public ActionResult ActiveConfirmed(int id)
        {
            HorarioEntrega horarioEntrega = db.HorarioEntrega.Find(id);
            horarioEntrega.Estado = "Activo";
            db.Entry(horarioEntrega).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RTS_Mensajeria/Controllers/OficinasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RTS_Mensajeria.Models.DB_Model;

namespace RTS_Mensajeria.Controllers
{
    public class OficinasController : BaseController
    {
        private RTS_MensajeriaEntities db = new RTS_MensajeriaEntities();

        // GET: Oficinas
        public ActionResult Index()
        {
            var oficina = db.Oficina.Include(o => o.Empresa).Include(o => o.Nivel);
            return View(oficina.ToList());
        }
        // GET: Oficinas
        public ActionResult Inactive()
        {
            var oficina = db.Oficina.Include(o => o.Empresa).Include(o => o.Nivel);
            return View(oficina.ToList());
        }

        // GET: Oficinas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oficina oficina = db.Oficina.Find(id);
            if (oficina == null)
            {
                return HttpNotFound();
            }
            return View(oficina);
        }

        // GET: Oficinas/Create
        public ActionResult Create()
        {
            ViewBag.Id_Empresa = new SelectList(db.Empresa, "Id_Empresa", "Nombre");
            ViewBag.Id_Nivel = new SelectList(db.Nivel, "Id_Nivel", "Descripcion");
            return View();
        }

        // POST: Oficinas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_Oficina,Id_Nivel,Id_Empresa,Ocupada,Nombre,Estado")] Oficina oficina)
        {
            if (ModelState.IsValid)
            {
                db.Oficina.Add(oficina);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Id_Empresa = new SelectList(db.Empresa, "Id_Empresa", "Nombre", oficina.Id_Empresa);
            ViewBag.Id_Nivel = new SelectList(db.Nivel, "Id_Nivel", "Descripcion", oficina.Id_Nivel);
            return View(oficina);
        }

        // GET: Oficinas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oficina oficina = db.Oficina.Find(id);
            if (oficina == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id_Empresa = new SelectList(db.Empresa, "Id_Empresa", "Nombre", oficina.Id_Empresa);
            ViewBag.Id_Nivel = new SelectList(db.Nivel, "Id_Nivel", "Descripcion", oficina.Id_Nivel);
            return View(oficina);
        }

        // POST: Oficinas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_Oficina,Id_Nivel,Id_Empresa,Ocupada,Nombre,Estado")] Oficina oficina)
        {
            if (ModelState.IsValid)
            {
                db.Entry(oficina).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Id_Empresa = new SelectList(db.Empresa, "Id_Empresa", "Nombre", oficina.Id_Empresa);
            ViewBag.Id_Nivel = new SelectList(db.Nivel, "Id_Nivel", "Descripcion", oficina.Id_Nivel);
            return View(oficina);
        }

        // GET: Oficinas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oficina oficina = db.Oficina.Find(id);
            if (oficina == null)
            {
                return HttpNotFound();
            }
            return View(oficina);
        }

        // POST: Oficinas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Oficina oficina = db.Oficina.Find(id);
            oficina.Estado = "Inactivo";
            db.Entry(oficina).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: Oficinas/Active/5
        public ActionResult Active(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Oficina oficina = db.Oficina.Find(id);
            if (oficina == null)
            {
                return HttpNotFound();
            }
            return View(oficina);
        }

        // POST: Oficinas/Active/5
        [HttpPost, ActionName("Active")]
        [ValidateAntiForgeryToken]
        public ActionResult ActiveConfirmed(int id)
        {
            Oficina oficina = db.Oficina.Find(id);
            oficina.Estado = "Activo";
            db.Entry(oficina).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RTS_Mensajeria/Views/HorarioEntregas/Active.cshtml
@model RTS_Mensajeria.Models.DB_Model.HorarioEntrega
@{
    ViewBag.Title = "Activar horario de entrega";
}
@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="card card-cascade narrower">
        <div class="view view-cascade primary-color narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
            <h4 class="ml-3 mb-2 mb-sm-0 pt-1 white-text">
                <span><a href="@Url.Action("Index","Home")" class="text-decoration-none white-text"><i class="fa fa-home mr-1"></i> Inicio</a></span>
                <span>/</span>
                <span><a href="@Url.Action("Index", "HorarioEntregas")" class="text-decoration-none white-text"><i class="fa fa-briefcase mr-1"></i> Horarios de entrega</a></span>
                <span>/</span>
                <span>Activar horario de entrega</span>
            </h4>
            <div class="mr-3">
                <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2">
                    <i class="fas fa-info-circle mt-0"></i>
                </button>
            </div>
        </div>
        <div class="px-4">
            <div class="table-wrapper">
                <br />
                <div class="row">
                    <div class="col-md-10">
                        <h2>Activar el horario de entrega</h2>
                    </div>
                </div>
                <hr />
                <div>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Hora_Entrega)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Hora_Entrega)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Hora_Salida)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Hora_Salida)
                        </dd>
                    </dl>
                    <hr />
                    <div class="text-center">
                        <h3>¿Desea activar éste horario de entrega?</h3>
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <a class="btn btn-primary" href="@Url.Action("Inactive", "HorarioEntregas")">
                                    <i class="fa fa-arrow-left mr-1"></i> Regresar
                                </a>
                                |
                                <button type="submit" class="btn btn-green green">
                                    <i class="fa fa-check mr-1"></i>
                                    Eliminar
                                </button>
                            </div>
                            <br />
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
}

RTS_Mensajeria/Views/HorarioEntregas/Create.cshtml
@model RTS_Mensajeria.Models.DB_Model.HorarioEntrega
@{
    ViewBag.Title = "Crear horario de entrega";
}
@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="card card-cascade narrower">
        <div class="view view-cascade primary-color narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
            <h4 class="ml-3 mb-2 mb-sm-0 pt-1 white-text">
                <span><a href="@Url.Action("Index","Home")" class="text-decoration-none white-text"><i class="fa fa-home mr-1"></i> Inicio</a></span>
                <span>/</span>
                <span><a href="@Url.Action("Index", "HorarioEntregas")" class="text-decoration-none white-text"><i class="fa fa-briefcase mr-1"></i> Horarios de entrega</a></span>
                <span>/</span>
                <span>Agregar horario de entrega</span>
            </h4>
            <div class="mr-3">
                <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2">
                    <i class="fas fa-info-circle mt-0"></i>
                </button>
            </div>
        </div>
        <div class="px-4">
            <div class="table-wrapper">
                <br />
                <div class="row">
                    <div class="col-md-10">
                        <h2>Nuevo horario de entrega</h2>
                    </div>
                </div>
                <hr />
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Estado, new { @Value = "Activo" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Hora_Entrega, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Hora_Entrega, new { htmlAttributes = new { @class = "form-control timepicker" } })
                                @Html.ValidationMessageFor(model => model.Hora_Entrega, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Hora_Salida, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Hora_Salida, new { htmlAttributes = new { @class = "form-control timepicker" } })
                                @Html.ValidationMessageFor(model => model.Hora_Salida, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <br />
                        <div class="form-group text-right">
                            <div class="col-md-offset-2 col-md-10">
                                <a class="btn btn-primary" href="@Url.Action("Index", "HorarioEntregas")"><i class="fa fa-arrow-left mr-1"></i> Regresar</a>
                                |
                                <button type="submit" class="btn btn-default"><i class="fas fa-magic ml-1"></i> Crear </button>
                            </div>
                        </div>
                    </div>
                }

                @section Scripts {
                    <script type="text/javascript">
                        $('#Hora_Entrega').pickatime({
                            autoclose: true,
                            'default': 'now',
                            donetext: 'Hecho',
                            twelvehour: false
                        });
                        $('#Hora_Salida').pickatime({
                            autoclose: true,
                            'default': 'now',
                            donetext: 'Hecho',
                            twelvehour: false
                        });
                    </script>
                }


            </div>
        </div>
    </div>
}

RTS_Mensajeria/Views/HorarioEntregas/Delete.cshtml
@model RTS_Mensajeria.Models.DB_Model.HorarioEntrega
@{
    ViewBag.Title = "Eliminar horario de entrega";
}
@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="card card-cascade narrower">
        <div class="view view-cascade primary-color narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
            <h4 class="ml-3 mb-2 mb-sm-0 pt-1 white-text">
                <span><a href="@Url.Action("Index","Home")" class="text-decoration-none white-text"><i class="fa fa-home mr-1"></i> Inicio</a></span>
                <span>/</span>
                <span><a href="@Url.Action("Index", "HorarioEntregas")" class="text-decoration-none white-text"><i class="fa fa-briefcase mr-1"></i> Horarios de entrega</a></span>
                <span>/</span>
                <span>Eliminar horario de entrega</span>
            </h4>
            <div class="mr-3">
                <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2">
                    <i class="fas fa-info-circle mt-0"></i>
                </button>
            </div>
        </div>
        <div class="px-4">
            <div class="table-wrapper">
                <br />
                <div class="row">
                    <div class="col-md-10">
                        <h2>Eliminar el horario de entrega</h2>
                    </div>
                </div>
                <hr />
                <div>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Hora_Entrega)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Hora_Entrega)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Hora_Salida)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Hora_Salida)
                        </dd>
                    </dl>
                    <hr />
                    <div class="text-center">
                        <h3>¿Desea eliminar éste horario de entrega?</h3>
                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-actions no-color">
                                <a class="btn btn-primary" href="@Url.Action("Index", "HorarioEntregas")">
                                    <i class="fa fa-arrow-left mr-1"></i> Regresar
                                </a>
                                |
                                <button type="submit" class="btn btn-default">
                                    <i class="fa fa-times mr-1"></i>
                                    Eliminar
                                </button>
                            </div>
                            <br />
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
}

RTS_Mensajeria/Views/HorarioEntregas/Details.cshtml
@model RTS_Mensajeria.Models.DB_Model.HorarioEntrega
@{
    ViewBag.Title = "Detalles del horario de entrega";
}

@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{

    <div class="card card-cascade narrower">
        <div class="view view-cascade primary-color narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
            <h4 class="ml-3 mb-2 mb-sm-0 pt-1 white-text">
                <span><a href="@Url.Action("Index","Home")" class="text-decoration-none white-text"><i class="fa fa-home mr-1"></i> Inicio</a></span>
                <span>/</span>
                <span><a href="@Url.Action("Index", "HorarioEntregas")" class="text-decoration-none white-text"><i class="fa fa-briefcase mr-1"></i> Horarios de entrega</a></span>
                <span>/</span>
                <span>Detalle del horario de entrega</span>
            </h4>
            <div class="mr-3">
                <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2">
                    <i class="fas fa-info-circle mt-0"></i>
                </button>
            </div>
        </div>
        <div class="px-4">
            <div class="table-wrapper">
                <br />
                <div class="row">
                    <div class="col-md-10">
                        <h2>Detalle del horario de entrega</h2>
                    </div>
                </div>
                <hr />
                <div>
                    <dl class="dl-horizontal">
                        <dt>
                            @Html.DisplayNameFor(model => model.Hora_Entrega)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Hora_Entrega)
                        </dd>

                        <dt>
                            @Html.DisplayNameFor(model => model.Hora_Salida)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Hora_Salida)
                        </dd>

                    </dl>
                </div>
                <br />
                <div class="form-group text-right">
                    <div class="col-md-offset-2 col-md-10">
                        <a class="btn btn-primary" href="@Url.Action("Index", "HorarioEntregas")"><i class="fa fa-arrow-left mr-1"></i> Regresar</a>
                        |
                        <a href="@Url.Action("Edit", "Oficinas", new { id = Model.Id_HorarioEntrega})" class="btn btn-default"><i class="fa fa-edit ml-1"></i> Editar </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

RTS_Mensajeria/Views/HorarioEntregas/Edit.cshtml
@model RTS_Mensajeria.Models.DB_Model.HorarioEntrega

@{
    ViewBag.Title = "Editar horario de entrega";
}

@if (!Request.IsAuthenticated)
{
    Response.Redirect(@Url.Action("Login", "Account"));
}
else
{
    <div class="card card-cascade narrower">
        <div class="view view-cascade primary-color narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
            <h4 class="ml-3 mb-2 mb-sm-0 pt-1 white-text">
                <span><a href="@Url.Action("Index","Home")" class="text-decoration-none white-text"><i class="fa fa-home mr-1"></i> Inicio</a></span>
                <span>/</span>
                <span><a href="@Url.Action("Index", "HorarioEntregas")" class="text-decoration-none white-text"><i class="fa fa-briefcase mr-1"></i> Horarios de entrega</a></span>
                <span>/</span>
                <span>Editar horario de entrega</span>
            </h4>
            <div class="mr-3">
                <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2">
                    <i class="fas fa-info-circle mt-0"></i>
                </button>
            </div>
        </div>
        <div class="px-4">
            <div class="table-wrapper">
                <br />
                <div class="row">
                    <div class="col-md-10">
                        <h2>Editar horario de entrega</h2>
                    </div>
                </div>
                <hr />
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        <h4>HorarioEntrega</h4>
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @Html.HiddenFor(model => model.Id_HorarioEntrega)
                        @Html.HiddenFor(model => model.Estado)
                        <div class="form-group">
                            @Html.LabelFor(model => model.Hora_Entrega, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Hora_Entrega, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Hora_Entrega, "", new { @class = "form-control timepicker" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Hora_Salida, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Hora_Salida, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Hora_Salida, "", new { @class = "form-control timepicker" })
                            </div>
                        </div>
                        <br />
                        <div class="form-group text-right">
                            <div class="col-md-offset-2 col-md-10">
                                <a class="btn btn-primary" href="@Url.Action("Index", "HorarioEntregas")"><i class="fa fa-arrow-left mr-1"></i> Regresar</a>
                                |
                                <button type="submit" class="btn btn-default"><i class="fa fa-save ml-1"></i> Guardar </button>
                            </div>
                        </div>
                    </div>
                }
                @section Scripts {
                    <script type="text/javascript">
                        $('#Hora_Entrega').pickatime({
                            autoclose: true,
                            'default': 'now',
                            donetext: 'Hecho',
                            twelvehour: false
                        });
                        $('#Hora_Salida').pickatime({
                            autoclose: true,
                            'default': 'now',
                            donetext: 'Hecho',
                            twelvehour: false
                        });
                    </script>
                }
            </div>
        </div>
    </div>
}