RTS_Mensajeria/Models/DB_Model/IngresoProveedor.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTS_Mensajeria.Models.DB_Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class IngresoProveedor : BaseVM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IngresoProveedor()
        {
            this.DetalleIngresoProveedor = new HashSet<DetalleIngresoProveedor>();
            this.RutaEntrega = new HashSet<RutaEntrega>();
        }
    
        public int Id_IngresoProveedor { get; set; }

        [Display(Name = "Código ingreso")]
        [DefaultValue("In-Pro-Co")]
        public string Codigo_IngresoProveedor { get; set; }
        
        [DisplayName("Proveedor")]
        [Required(ErrorMessage = "Debe seleccionar el proveedor")]
        public int Id_Proveedor { get; set; }
        public Nullable<int> Id_Usuario { get; set; }

        [DisplayName("Horario de entrega")]
        [Required(ErrorMessage = "Debe seleccionar el horario de entrega")]
        public int Id_HorarioEntrega { get; set; }
        
        [Display(Name = "Fecha de ingreso")]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Debe ingresar la fecha de ingreso")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Fecha_Ingreso { get; set; }

        //Ingresar fecha por defecto, del servidor no del cliente
        [Display(Name = "Fecha de creación")]
        [DataType(DataType.Date)]
        [Required(ErrorMessage = "Debe ingresar la fecha de ingreso")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }

        [DataType(DataType.MultilineText)]
        [Display(Name = "Descripción del ingreso")]
        [Required(ErrorMessage = "Debe ingresar la descripción del ingreso")]
        public string Detalle_Ingreso { get; set; }

        [DataType(DataType.MultilineText)]
        [Display(Name = "Descripción del producto")]
        [Required(ErrorMessage = "Debe ingresar la descripción del producto")]
        public string Detalle_Producto { get; set; }

        [Display(Name = "Número de paquetes")]
        [Required(ErrorMessage = "Debe ingresar la cantidad de paquetes")]
        public Nullable<int> No_Paquetes { get; set; }

        [DefaultValue("No")]
        [StringLength(2, MinimumLength = 2)]
        [Required(ErrorMessage = "Debe seleccionar si usará el elevador")]
        public string Elevador { get; set; }

        [DefaultValue("No")]
        [StringLength(2, MinimumLength = 2)]
        [Required(ErrorMessage = "Debe seleccionar la aprobación")]
        public string Aprobada { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleIngresoProveedor> DetalleIngresoProveedor { get; set; }
        public virtual HorarioEntrega HorarioEntrega { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RutaEntrega> RutaEntrega { get; set; }
    }
}

RTS_Mensajeria/Models/DB_Model/RutaEntrega.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTS_Mensajeria.Models.DB_Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class RutaEntrega : BaseVM
    {
        public int Id_RutaEntrega { get; set; }

        [DisplayName("Ingreso")]
        public Nullable<int> Id_Ingreso { get; set; }

        [DisplayName("Solicitud de proveedor")]
        public Nullable<int> Id_SolicitudProveedor { get; set; }

        //Ascendente, Descendente
        [Display(Name = "Orden")]
        [StringLength(11, MinimumLength = 10)]
        [Required(ErrorMessage = "Debe seleccionar el orden")]
        public string Orden { get; set; }

        [DefaultValue("No")]
        [StringLength(2, MinimumLength = 2)]
        [Required(ErrorMessage = "Debe seleccionar si se anticipará")]
        public string Anticipada { get; set; }
    
        public virtual Ingreso Ingreso { get; set; }
        public virtual IngresoProveedor IngresoProveedor { get; set; }
    }
}

RTS_Mensajeria/Controllers/RutaEntregasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using RTS_Mensajeria.Models.DB_Model;

namespace RTS_Mensajeria.Controllers
{
    public class RutaEntregasController : BaseController
    {
        private RTS_MensajeriaEntities db = new RTS_MensajeriaEntities();

        // GET: RutaEntregas
        public ActionResult Index()
        {
            var rutaEntrega = db.RutaEntrega.Include(r => r.Ingreso).Include(r => r.IngresoProveedor);
            return View(rutaEntrega.ToList());
        }

        // GET: RutaEntregas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RutaEntrega rutaEntrega = db.RutaEntrega.Find(id);
            if (rutaEntrega == null)
            {
                return HttpNotFound();
            }
            return View(rutaEntrega);
        }

        // GET: RutaEntregas/Create
        public ActionResult Create()
        {
            ViewBag.Id_Ingreso = new SelectList(db.Ingreso, "Id_Ingreso", "Codigo_Ingreso");
            ViewBag.Id_SolicitudProveedor = new SelectList(db.IngresoProveedor, "Id_IngresoProveedor", "Codigo_IngresoProveedor");
            return View();
        }

        // POST: RutaEntregas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id_RutaEntrega,Id_Ingreso,Id_SolicitudProveedor,Orden,Anticipada")] RutaEntrega rutaEntrega)
        {
            if (ModelState.IsValid)
            {
                db.RutaEntrega.Add(rutaEntrega);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Id_Ingreso = new SelectList(db.Ingreso, "Id_Ingreso", "Codigo_Ingreso", rutaEntrega.Id_Ingreso);
            ViewBag.Id_SolicitudProveedor = new SelectList(db.IngresoProveedor, "Id_IngresoProveedor", "Codigo_IngresoProveedor", rutaEntrega.Id_SolicitudProveedor);
            return View(rutaEntrega);
        }

        // GET: RutaEntregas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RutaEntrega rutaEntrega = db.RutaEntrega.Find(id);
            if (rutaEntrega == null)
            {
                return HttpNotFound();
            }
            ViewBag.Id_Ingreso = new SelectList(db.Ingreso, "Id_Ingreso", "Codigo_Ingreso", rutaEntrega.Id_Ingreso);
            ViewBag.Id_SolicitudProveedor = new SelectList(db.IngresoProveedor, "Id_IngresoProveedor", "Codigo_IngresoProveedor", rutaEntrega.Id_SolicitudProveedor);
            return View(rutaEntrega);
        }

        // POST: RutaEntregas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id_RutaEntrega,Id_Ingreso,Id_SolicitudProveedor,Orden,Anticipada")] RutaEntrega rutaEntrega)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rutaEntrega).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Id_Ingreso = new SelectList(db.Ingreso, "Id_Ingreso", "Codigo_Ingreso", rutaEntrega.Id_Ingreso);
            ViewBag.Id_SolicitudProveedor = new SelectList(db.IngresoProveedor, "Id_IngresoProveedor", "Codigo_IngresoProveedor", rutaEntrega.Id_SolicitudProveedor);
            return View(rutaEntrega);
        }

        // GET: RutaEntregas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RutaEntrega rutaEntrega = db.RutaEntrega.Find(id);
            if (rutaEntrega == null)
            {
                return HttpNotFound();
            }
            return View(rutaEntrega);
        }

        // POST: RutaEntregas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RutaEntrega rutaEntrega = db.RutaEntrega.Find(id);
            db.RutaEntrega.Remove(rutaEntrega);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

RTS_Mensajeria/Controllers/VistasRecepcionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RTS_Mensajeria.Controllers
{
    public class VistasRecepcionController : Controller
    {
        // GET: VistasRecepcion
        public ActionResult AdministrarProveedores()
        {
            return View();
        }
        public ActionResult AdministrarIngresoProveedor()
        {
            return View();
        }
        public ActionResult AdministrarSalidaProveedor()
        {
            return View();
        }

        public ActionResult SolicitudesIngreso()
        {
            return View();
        }

        public ActionResult RechazarSolicitud()
        {
            return View();
        }

        public ActionResult AceptarSolicitud()
        {
            return View();
        }

        public ActionResult IngresoProveedor()
        {
            return View();
        }

        public ActionResult RutaEntrega()
        {
            return View();
        }

        public ActionResult PaquetesEntregados()
        {
            return View();
        }

        public ActionResult VisitasProveedorAutorizadas()
        {
            return View();
        }
        
        public ActionResult VisitasProveedor()
        {
            return View();
        }
    }
}

RTS_Mensajeria/Views/VistasRecepcion/IngresoProveedor.cshtml
@model RTS_Mensajeria.Models.DB_Model.IngresoProveedor

@{
    ViewBag.Title = "Create";
}
<div class="card card-cascade narrower">
    <div class="view view-cascade primary-color narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
        <h4 class="ml-3 mb-2 mb-sm-0 pt-1 white-text">
            <span><a href="@Url.Action("Index","Home")" class="text-decoration-none white-text"><i class="fa fa-home mr-1"></i> Inicio</a></span>
            <span>/</span>
            <span><a href="@Url.Action("SolicitudIngresos", "VistasNormal")" class="text-decoration-none white-text"><i class="fa fa-truck mr-1"></i> Proveedores</a></span>
            <span>/</span>
            <span>Agregar ingreso</span>
        </h4>
        <div class="mr-3">
            <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2">
                <i class="fas fa-info-circle mt-0"></i>
            </button>
        </div>
    </div>
    <div class="px-4">
        <div class="table-wrapper">
            <br />
            <div class="row">
                <div class="col-md-10">
                    <h2>Nuevo ingreso mensajero</h2>
                </div>
            </div>
            <hr />
            <br />
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    <br />
                    <div class="col-md-10">
                        <select class="mdb-select colorful-select dropdown-primary md-form" searchable="Buscar un proveedor ">
                            <option value="" disabled selected>Seleccione un proveedor</option>
                            <option value="1">Intelaf</option>
                            <option value="2">Cemaco</option>
                            <option value="3">Ferreteria B</option>
                            <option value="3">Empresa 4</option>
                            <option value="3">Proveedor confianza</option>
                            <option value="142">ABCO</option>
                            <option value="3566">ABEDUSA</option>
                            <option value="1698">ABG PUBLICIDAD</option>
                            <option value="2050">ABINSA</option>
                            <option value="384">ABSA</option>
                            <option value="2100">ACEROS SUECOS</option>
                            <option value="1759">ACI</option>
                            <option value="2213">ACIAC</option>
                            <option value="3413">ACISA</option>
                            <option value="2019">ACQUARONI</option>
                            <option value="1906">ACR GUATEMALA</option>
                            <option value="175">ACTIVA</option>
                            <option value="1903">ACUATICA</option>
                            <option value="262">ADARA</option>
                            <option value="2056">ADAVANCE TECH</option>
                            <option value="3706">ADBYSER</option>
                            <option value="196">ADCO</option>
                            <option value="2024">ADECO</option>
                            <option value="1481">ADEPSA</option>
                            <option value="1752">ADISA</option>
                            <option value="36">ADMARK</option>
                            <option value="1425">ADMINISTRACION GLOBAL Y SERVICIOS</option>
                            <option value="1585">ADMINISTRADORA DIMO</option>
                            <option value="2195">ADRI</option>
                            <option value="3760">ADVANCE</option>
                            <option value="2328">ADVSER</option>
                            <option value="1966">AEI GUATEMALA</option>
                            <option value="1863">AEROBOTS</option>
                            <option value="2268">AF FUMIGACION</option>
                            <option value="312">AFILADURIA SAN JUAN</option>
                            <option value="266">AFSA</option>
                            <option value="3683">AGENCIA</option>
                            <option value="3579">AGENCIA DE VIAJES</option>
                            <option value="1853">AGENCIA INDUSTRIAL Y MERCANTIL</option>
                            <option value="3671">AGENCIA Y FABRICA HONDA</option>
                            <option value="2245">AGENCIAS CEIBA CRUZ</option>
                            <option value="2317">AGENCIAS J I COHEN</option>
                            <option value="3789">AGENSE</option>
                            <option value="1729">AGRICOL AMSA</option>
                            <option value="2189">AGRICOLA AMSA</option>
                            <option value="2199">AGRO GANADERA SANTA MARGARITA</option>
                            <option value="2097">AGROCENTRO</option>
                            <option value="114">AGROCHINA</option>
                            <option value="3431">AGROCTIMA</option>
                            <option value="2004">AGROFORTEX</option>
                            <option value="2276">AGROINCO</option>
                            <option value="44">AGROINDUSTRIAS VALENCIA S.A.</option>
                            <option value="2310">AGROKTIMA</option>
                            <option value="1745">AGROPECUARIA BELLA ISLA</option>
                            <option value="2296">AGROPECUARIA EL ESCORIAL</option>
                            <option value="2142">AGROPECUARIA EL TESORO</option>
                            <option value="2348">AGROPTIMA</option>
                            <option value="1727">AGT</option>
                            <option value="144">AGUA PURA SALVAVIDAS</option>
                            <option value="1611">AGUA PURA SCANDIA</option>

                        </select>
                        <label class="mdb-main-label">Proveedor</label>
                    </div>
                </div>

                <div class="form-group">
                    <br />
                    <div class="col-md-10">
                        <select class="mdb-select colorful-select dropdown-primary md-form" searchable="Buscar una empresa ">
                            <option value="" disabled selected>Seleccione una empresa</option>
                            <option value="1">Intelaf</option>
                            <option value="2">Cemaco</option>
                            <option value="3">Ferreteria B</option>
                            <option value="3">Empresa 4</option>
                            <option value="3">Proveedor confianza</option>
                            <option value="142">ABCO</option>
                            <option value="3566">ABEDUSA</option>
                            <option value="1698">ABG PUBLICIDAD</option>
                            <option value="2050">ABINSA</option>
                            <option value="384">ABSA</option>
                            <option value="2100">ACEROS SUECOS</option>

                        </select>
                        <label class="mdb-main-label">Empresa</label>
                    </div>
                </div>

                <div class="form-group">
                    <br />
                    <div class="col-md-10">
                        <!-- Material input -->
                        <div class="md-form">
                            <input type="text" id="form1" class="form-control">
                            <label for="form1">Nombre mensajero</label>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <br />
                    <div class="col-md-10">
                        <!-- Material input -->
                        <div class="md-form">
                            <input type="text" id="form13" class="form-control">
                            <label for="form13">Número de identificación (DPI/CUI)</label>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <br />
                    <div class="col-md-10">
                        <!-- Material input -->
                        <div class="md-form">
                            <input type="text" id="form12" class="form-control">
                            <label for="form12">Gafete</label>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <br />
                    <div class="col-md-10">
                        <!-- Material inline 1 -->
                        <div class="form-check form-check-inline">
                            <input type="radio" class="form-check-input" id="materialInline1" name="inlineMaterialRadiosExample">
                            <label class="form-check-label" for="materialInline1">Salida</label>
                        </div>

                        <!-- Material inline 2 -->
                        <div class="form-check form-check-inline">
                            <input type="radio" class="form-check-input" id="materialInline2" name="inlineMaterialRadiosExample">
                            <label class="form-check-label" for="materialInline2">Entrada</label>
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <br />
                    <div class="col-md-10">
                        <div class="md-form">
                            <input placeholder="Seleccione una fecha" type="text" id="date-picker-example" class="form-control datepicker">
                            <label for="date-picker-example">Fecha de ingreso</label>
                        </div>
                    </div>
                </div>

                <div class="form-group text-right">
                    <br />
                    <div class="col-md-offset-2 col-md-10">
                        <a class="btn btn-primary" href="@Url.Action("SolicitudesIngreso", "VistasRecepcion")"><i class="fa fa-arrow-left mr-1"></i> Regresar</a>
                        |
                        <button type="submit" class="btn btn-default"><i class="fas fa-magic ml-1"></i> Crear </button>
                    </div>
                </div>
            </div>
            @section Scripts {
                @Scripts.Render("~/bundles/jqueryval")

                <script>

                    // Data Picker Initialization
                    $('.datepicker').pickadate();
                </script>
            }
        </div>
    </div>
</div>

RTS_Mensajeria/Views/VistasRecepcion/SolicitudesIngreso.cshtml
@{
    ViewBag.Title = "Administrar Proveedores";
}
<div class="card card-cascade narrower">
    <div class="view view-cascade primary-color narrower py-2 mx-4 mb-3 d-flex justify-content-between align-items-center">
        <h4 class="ml-3 mb-2 mb-sm-0 pt-1 white-text">
            <span><a href="@Url.Action("Index","Home")" class="text-decoration-none white-text"><i class="fa fa-home mr-1"></i> Inicio</a></span>
            <span>/</span>
            <span><i class="fa fa-truck mr-1"></i> Proveedores</span>
        </h4>
        <div class="mr-3">
            <button type="button" class="btn btn-outline-white btn-rounded btn-sm px-2">
                <i class="fas fa-info-circle mt-0"></i>
            </button>
        </div>
    </div>
    <div class="px-4">
        <div class="table-wrapper">
            <br />
            <div class="row">
                <div class="col-md-10">
                    <h2>Administrar ingresos/salidas mensajeros</h2>
                </div>
                <div class="col-md-2">
                    <a class="btn btn-default btn-small btn-rounded" href="@Url.Action("IngresoProveedor", "VistasRecepcion")">
                        <i class="fa fa-plus"></i> Nuevo
                    </a>
                </div>
            </div>
            <br />
            <div class="table-responsive ">

                <table class="table table-hover">
                    <tr>
                        <th>
                            Código Ingreso
                        </th>
                        <th>Proveedor</th>
                        <th>Empresa</th>
                        <th>Hora</th>
                        <th>
                            Nombre
                        </th>
                        <th>
                            CUI
                        </th>
                        <th>
                            Carnet
                        </th>
                        <th>
                            Tipo
                        </th>
                        <th>Acciones</th>
                    </tr>
                    <tr>
                        <td>
                            SOIN0001
                        </td>
                        <td>
                            Intelaf
                        </td>
                        <td>Tigo</td>
                        <td>30/05/2019 7:00</td>
                        <td>
                            John Doe
                        </td>
                        <td>
                            0000 00000 0000
                        </td>
                        <td>
                            GA02
                        </td>
                        <td>Entrada</td>
                        <td>
                            <a class="btn btn-sm btn-rounded blue">
                                <i class="fa fa-eye"></i> Detalle
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            SOIN0001
                        </td>
                        <td>
                            Intelaf
                        </td>
                        <td>Tigo</td>
                        <td>30/05/2019 8:00</td>
                        <td>
                            John Doe
                        </td>
                        <td>
                            0000 00000 0000
                        </td>
                        <td>
                            GA02
                        </td>
                        <td>Salida</td>
                        <td>
                            <a class="btn btn-sm btn-rounded blue">
                                <i class="fa fa-eye"></i> Detalle
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            SOIN0003
                        </td>
                        <td>
                            Samsung
                        </td>
                        <td>Electonicabp</td>
                        <td>30/05/2019 9:00</td>
                        <td>
                            Pablo Dan
                        </td>
                        <td>
                            0000 00000 0000
                        </td>
                        <td>
                            GA023
                        </td>
                        <td>Entrada</td>
                        <td>
                            <a class="btn btn-sm btn-rounded blue">
                                <i class="fa fa-eye"></i> Detalle
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            SOIN0021
                        </td>
                        <td>
                            Cemaco
                        </td>
                        <td>Muebles España</td>
                        <td>30/05/2019 9:18</td>
                        <td>
                            Jane Dan
                        </td>
                        <td>
                            0000 00000 0000
                        </td>
                        <td>
                            GA087
                        </td>
                        <td>Salida</td>
                        <td>
                            <a class="btn btn-sm btn-rounded blue">
                                <i class="fa fa-eye"></i> Detalle
                            </a>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>
</br/>